name: "SonarQube Badge"
description: 'SonarQube Badge'
inputs:
  directory:
    description: 'Directory where badges will be generated'
    required: false
    default: '.badges'
  metrics:
    description: 'Target metrics to be generated, comma-separated'
    required: false
    default: 'all'
  svgFrom:
    description: 'Source of SVG badge images'
    type: choice
    required: false
    default: 'shields.io'
    options:
      - sonarqube
      - shields.io
outputs:
  list:
    description: 'Result list'
    value: ${{ steps.result.outputs.list }}
  markdown:
    description: 'Markdown'
    value: ${{ steps.result.outputs.markdown }}

runs:
  using: "composite"
  steps:
    - name: Setting up inputs
      shell: bash
      run: |
        # Setting up inputs
        TARGET_DIRECTORY="${{ inputs.directory }}"
        TARGET_METRICS="${{ inputs.metrics }}"
        TARGET_SVG_FROM="${{ inputs.svgFrom }}"
        echo "TARGET_DIRECTORY=$TARGET_DIRECTORY" >> $GITHUB_ENV
        echo "TARGET_METRICS=$TARGET_METRICS" >> $GITHUB_ENV
        echo "TARGET_SVG_FROM=$TARGET_SVG_FROM" >> $GITHUB_ENV

    - name: Generate Badges
      shell: bash
      run: |
        # Run badge.svg.sonarqube.sh
        ${GITHUB_ACTION_PATH}/badge.svg.sonarqube.sh

    - name: Commit badges
      shell: bash
      run: |
        # Commit badges
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git remote set-url origin "https://$GITHUB_ACTOR:${{ env.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git add ${{ env.TARGET_DIRECTORY }}
        if ! git diff-index --quiet HEAD --; then
          git commit -m "chore: generate badges on $GITHUB_SHA" -q
        fi
        git push -u origin ${{ env.GITHUB_REF_NAME }}

    - name: Set outputs
      id: result
      shell: bash
      run: |
        echo 'list<<EOF' >> $GITHUB_OUTPUT
        ${GITHUB_ACTION_PATH}/print-result.sh list >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

        echo 'markdown<<EOF' >> $GITHUB_OUTPUT
        ${GITHUB_ACTION_PATH}/print-result.sh markdown >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
