
name: Unit Test

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'src/**.ts'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Test with coverage
        run: |
          npx jest --coverage

      - name: Scan Analysis
        uses: docker://sonarsource/sonar-scanner-cli:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: badge action
        uses: jadewon/sonar-badge@v1
        id: badge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          metrics: all

      - name: print outputs
        run: |
          echo "- print outputs"
          echo "outputs.markdown:"
          echo "${{ steps.badge.outputs.markdown }}"
          echo "outputs.list:"
          echo "${{ steps.badge.outputs.list }}"